default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: BloodDonor_development

test:
  <<: *default
  database: BloodDonor_test

production:
  <<: *default
  database: BloodDonor_production
  username: BloodDonor
  password: <%= ENV['BLOODDONOR_DATABASE_PASSWORD'] %>