default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: BloodDonar_development

test:
  <<: *default
  database: BloodDonar_test

production:
  <<: *default
  database: BloodDonar_production
  username: BloodDonar
  password: <%= ENV['BLOODDONAR_DATABASE_PASSWORD'] %>